# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0008_auto_20170607_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='id',
        ),
        migrations.AlterField(
            model_name='demo',
            name='identificador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='escalas.Identificador'),
        ),
    ]
