# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0010_auto_20170608_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='falta',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha de Alta'),
        ),
    ]
