# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0011_auto_20170608_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='laboral',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Baja temporal'), ('3', 'Sin trabajo actual'), ('4', 'Pensionista'), ('5', 'Nunca ha trabajado'), ('6', 'Desconocido')], max_length=1, verbose_name='Situación laboral'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de hijos'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', 'AIS Gracia'), ('2', 'AIS Dreta'), ('3', 'AIS Guinardó')], max_length=1, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='dispalta',
            field=models.CharField(blank=True, choices=[(0, 'Domicilio'), (1, 'CESMA'), (2, 'H de dia'), (3, 'Subagudos'), (4, 'Agudos'), (5, 'Otros')], max_length=2, verbose_name='Dispositivo de alta'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='falta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='fing',
            field=models.DateField(blank=True, verbose_name='Fecha de Ingreso'),
        ),
    ]
