# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-08 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0012_auto_20170608_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='dispalta',
            field=models.CharField(blank=True, choices=[('0', 'Domicilio'), ('1', 'CESMA'), ('2', 'H de dia'), ('3', 'Subagudos'), ('4', 'Agudos'), ('5', 'Otros')], max_length=2, verbose_name='Dispositivo de alta'),
        ),
    ]
