# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0013_auto_20170608_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demo',
            options={'verbose_name': 'Demogr\xe1fico', 'verbose_name_plural': 'Demogr\xe1ficos'},
        ),
        migrations.RemoveField(
            model_name='demo',
            name='sector',
        ),
        migrations.AddField(
            model_name='ingreso',
            name='procedencia',
            field=models.CharField(blank=True, choices=[(b'00', b'Urgencias'), (b'01', b'Sala B2'), (b'02', b'CSMA'), (b'03', b'H de d\xc3\xada'), (b'04', b'CCEE'), (b'05', b'Subagudos'), (b'06', b'Otros')], max_length=2, verbose_name=b'Procedencia'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='sector',
            field=models.CharField(blank=True, choices=[(b'1', b'AIS Gracia'), (b'2', b'AIS Dreta'), (b'3', b'AIS Guinard\xc3\xb3')], max_length=1, verbose_name=b'Sector'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='laboral',
            field=models.CharField(blank=True, choices=[(b'1', b'Activo'), (b'2', b'Baja temporal'), (b'3', b'Sin trabajo actual'), (b'4', b'Pensionista'), (b'5', b'Nunca ha trabajado'), (b'6', b'Desconocido')], max_length=1, verbose_name=b'Situaci\xc3\xb3n laboral'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'N\xc3\xbamero de hijos'),
        ),
    ]
