# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0014_auto_20170609_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demo',
            name='laboral',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Baja temporal'), ('3', 'Sin trabajo actual'), ('4', 'Pensionista'), ('5', 'Nunca ha trabajado'), ('6', 'Desconocido')], max_length=1, verbose_name='Situación laboral'),
        ),
        migrations.AlterField(
            model_name='demo',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de hijos'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('00', 'Urgencias'), ('01', 'Sala B2'), ('02', 'CSMA'), ('03', 'H de día'), ('04', 'CCEE'), ('05', 'Subagudos'), ('06', 'Otros')], max_length=2, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', 'AIS Gracia'), ('2', 'AIS Dreta'), ('3', 'AIS Guinardó')], max_length=1, verbose_name='Sector'),
        ),
    ]
