# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0016_auto_20170610_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmaco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmaco', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_inicio', models.DateField()),
                ('f_termino', models.DateField(blank=True)),
                ('motivo', models.CharField(blank=True, choices=[('00', 'Falta de eficacia'), ('01', 'Efecto adverso EP'), ('02', 'Efecto adverso digestivo'), ('03', 'Efecto adverso neurológico'), ('04', 'Efecto adevrso otros'), ('05', 'Cambio dentro del mismo grupo'), ('06', 'Abandono del paciente')], max_length=2, verbose_name='Motivo de suspensión')),
                ('farmaco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalas.Farmaco')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalas.Identificador')),
            ],
        ),
    ]
