# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0017_farmaco_tratamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
