# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0018_tratamiento_mg_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='f_termino',
            field=models.DateField(blank=True, null=True),
        ),
    ]
