# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0019_auto_20170610_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='f_inicio',
            field=models.DateField(verbose_name='Fecha de incio'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='f_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.PositiveSmallIntegerField(verbose_name='mg/dia'),
        ),
    ]
