# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0020_auto_20170610_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico_pac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_dg', models.DateField(verbose_name='Fecha diagnostico')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalas.Diagnostico')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalas.Identificador')),
            ],
        ),
    ]
