# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 13:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0021_diagnostico_diagnostico_pac'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnostico_pac',
            options={'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
    ]
