# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0022_auto_20170611_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='identificador',
        ),
        migrations.AddField(
            model_name='identificador',
            name='dispalta',
            field=models.CharField(blank=True, choices=[('0', 'Domicilio'), ('1', 'CESMA'), ('2', 'H de dia'), ('3', 'Subagudos'), ('4', 'Agudos'), ('5', 'Otros')], max_length=2, verbose_name='Dispositivo de alta'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='e_civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Pareja estable'), ('4', 'Separado'), ('5', 'Viudo'), ('6', 'Otro')], max_length=1, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='estudios',
            field=models.CharField(blank=True, choices=[('1', 'Primarios'), ('2', 'Secundarios'), ('3', 'Superiores'), ('4', 'Sin estudios'), ('5', 'Desconocido')], max_length=1, verbose_name='Nivel de estudios'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='falta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Alta'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='fnac',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 6, 11, 13, 41, 50, 668534, tzinfo=utc), verbose_name='Fecha de Nac.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='identificador',
            name='laboral',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Baja temporal'), ('3', 'Sin trabajo actual'), ('4', 'Pensionista'), ('5', 'Nunca ha trabajado'), ('6', 'Desconocido')], max_length=1, verbose_name='Situación laboral'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de hijos'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('00', 'Urgencias'), ('01', 'Sala B2'), ('02', 'CSMA'), ('03', 'H de día'), ('04', 'CCEE'), ('05', 'Subagudos'), ('06', 'Otros')], max_length=2, verbose_name='Procedencia'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', 'AIS Gracia'), ('2', 'AIS Dreta'), ('3', 'AIS Guinardó')], max_length=1, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='sexo',
            field=models.CharField(blank=True, choices=[('1', 'Masculino'), ('2', 'Femenino')], max_length=2),
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
        migrations.DeleteModel(
            name='Ingreso',
        ),
    ]
