# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0023_auto_20170611_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='fnac',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nac.'),
        ),
    ]
