# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0025_auto_20170613_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='dispalta',
            field=models.CharField(blank=True, choices=[(b'0', b'Domicilio'), (b'1', b'CSMA'), (b'2', b'H de dia'), (b'3', b'Subagudos'), (b'4', b'Agudos'), (b'5', b'CCEE Sant Pau'), (b'6', b'Otros')], max_length=2, verbose_name=b'Dispositivo de alta'),
        ),
    ]
