# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0026_auto_20170613_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='dispalta',
            field=models.CharField(blank=True, choices=[('0', 'Domicilio'), ('1', 'CSMA'), ('2', 'H de dia'), ('3', 'Subagudos'), ('4', 'Agudos'), ('5', 'CCEE Sant Pau'), ('6', 'Otros')], max_length=2, verbose_name='Dispositivo de alta'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='laboral',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Baja temporal'), ('3', 'Sin trabajo actual'), ('4', 'Pensionista'), ('5', 'Nunca ha trabajado'), ('6', 'Desconocido'), ('7', 'Estudiante')], max_length=1, verbose_name='Situación laboral'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de hijos'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('00', 'Urgencias'), ('01', 'Sala B2'), ('02', 'CSMA'), ('03', 'H de día'), ('04', 'CCEE'), ('05', 'Subagudos'), ('06', 'Otros')], max_length=2, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', 'AIS Gracia'), ('2', 'AIS Dreta'), ('3', 'AIS Guinardó')], max_length=1, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='f_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de término'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('00', 'Falta de eficacia'), ('01', 'Efecto adverso EP'), ('02', 'Efecto adverso digestivo'), ('03', 'Efecto adverso neurológico'), ('04', 'Efecto adevrso otros'), ('05', 'Cambio dentro del mismo grupo'), ('06', 'Abandono del paciente')], max_length=2, verbose_name='Motivo de suspensión'),
        ),
    ]
