# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0027_auto_20170613_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Csq8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(choices=[(b'PAC', b'Usuario'), (b'FAM', b'Familiar')], max_length=3)),
                ('item_01', models.PositiveSmallIntegerField(null=True)),
                ('item_02', models.PositiveSmallIntegerField(null=True)),
                ('item_03', models.PositiveSmallIntegerField(null=True)),
                ('item_04', models.PositiveSmallIntegerField(null=True)),
                ('item_05', models.PositiveSmallIntegerField(null=True)),
                ('item_06', models.PositiveSmallIntegerField(null=True)),
                ('item_07', models.PositiveSmallIntegerField(null=True)),
                ('item_08', models.PositiveSmallIntegerField(null=True)),
                ('item_09', models.PositiveSmallIntegerField(null=True)),
                ('item_10', models.TextField(null=True)),
                ('item_11', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='identificador',
            name='laboral',
            field=models.CharField(blank=True, choices=[(b'1', b'Activo'), (b'2', b'Baja temporal'), (b'3', b'Sin trabajo actual'), (b'4', b'Pensionista'), (b'5', b'Nunca ha trabajado'), (b'6', b'Desconocido'), (b'7', b'Estudiante')], max_length=1, verbose_name=b'Situaci\xc3\xb3n laboral'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'N\xc3\xbamero de hijos'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='procedencia',
            field=models.CharField(blank=True, choices=[(b'00', b'Urgencias'), (b'01', b'Sala B2'), (b'02', b'CSMA'), (b'03', b'H de d\xc3\xada'), (b'04', b'CCEE'), (b'05', b'Subagudos'), (b'06', b'Otros')], max_length=2, verbose_name=b'Procedencia'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='sector',
            field=models.CharField(blank=True, choices=[(b'1', b'AIS Gracia'), (b'2', b'AIS Dreta'), (b'3', b'AIS Guinard\xc3\xb3')], max_length=1, verbose_name=b'Sector'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='f_termino',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha de t\xc3\xa9rmino'),
        ),
        #migrations.AlterField(
        #    model_name='tratamiento',
        #    name='mg_dia',
        #    field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name=b'mg/dia'),
        #),
        migrations.AlterField(
            model_name='tratamiento',
            name='motivo',
            field=models.CharField(blank=True, choices=[(b'00', b'Falta de eficacia'), (b'01', b'Efecto adverso EP'), (b'02', b'Efecto adverso digestivo'), (b'03', b'Efecto adverso neurol\xc3\xb3gico'), (b'04', b'Efecto adevrso otros'), (b'05', b'Cambio dentro del mismo grupo'), (b'06', b'Abandono del paciente')], max_length=2, verbose_name=b'Motivo de suspensi\xc3\xb3n'),
        ),
    ]
