# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0028_auto_20170616_0811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csq8',
            options={'verbose_name': 'CSQ-8', 'verbose_name_plural': 'Escalas CSQ-8'},
        ),
        migrations.RemoveField(
            model_name='csq8',
            name='item_11',
        ),
        migrations.AlterField(
            model_name='csq8',
            name='autor',
            field=models.CharField(max_length=3),
        ),
    ]
