# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0029_auto_20170616_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'mg/dia'),
        ),
    ]
