# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0031_auto_20170617_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efecto', models.CharField(max_length=200, verbose_name='Efecto adverso')),
            ],
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='motivo',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='efectos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalas.Adverso'),
        ),
    ]
