# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0032_auto_20170617_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='dispalta',
            field=models.CharField(blank=True, choices=[('0', 'Domicilio'), ('1', 'CSMA'), ('2', 'H de dia'), ('3', 'Subagudos'), ('4', 'Agudos'), ('5', 'CCEE Sant Pau'), ('9', 'Otros')], max_length=2, verbose_name='Dispositivo de alta'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='e_civil',
            field=models.CharField(blank=True, choices=[('1', 'Soltero'), ('2', 'Casado'), ('3', 'Pareja estable'), ('4', 'Separado'), ('5', 'Viudo'), ('9', 'Otro')], max_length=1, verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='laboral',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Baja temporal'), ('3', 'Sin trabajo actual'), ('4', 'Pensionista'), ('5', 'Nunca ha trabajado'), ('6', 'Estudiante'), ('9', 'Desconocido')], max_length=1, verbose_name='Situación laboral'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('00', 'Urgencias'), ('01', 'Sala B2'), ('02', 'CSMA'), ('03', 'H de día'), ('04', 'CCEE'), ('05', 'Subagudos'), ('99', 'Otros')], max_length=2, verbose_name='Procedencia'),
        ),
    ]
