# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0033_auto_20170617_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='mg/dia'),
        ),
    ]
