# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0034_auto_20170617_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motivo_termino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efecto', models.CharField(max_length=200, verbose_name='Motivo de término de tratamiento')),
            ],
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='efectos',
        ),
        migrations.DeleteModel(
            name='Adverso',
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='motivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='escalas.Motivo_termino'),
        ),
    ]
