# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0035_auto_20170617_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='depot',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('01', 'Abandono de tratamiento'), ('02', 'Falta de eficacia'), ('03', 'Efecto adverso EP'), ('04', 'Efecto adverso digestivo'), ('05', 'Efecto adverso hematologico'), ('06', 'Efecto adverso autonómico'), ('07', 'Otro efecto adverso'), ('99', 'NE')], max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='Motivo_termino',
        ),
    ]
