# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0036_auto_20170617_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='depot',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
