# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0037_auto_20170617_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('icg_ge', models.PositiveSmallIntegerField(null=True)),
                ('quien_ge', models.CharField(max_length=3)),
                ('icg_mg', models.PositiveSmallIntegerField(null=True)),
                ('quien_mg', models.CharField(max_length=3)),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escalas.Identificador')),
            ],
            options={
                'verbose_name': 'escala ICG',
                'verbose_name_plural': 'escalas ICG',
            },
        ),
        migrations.RemoveField(
            model_name='cgi',
            name='identificador',
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='depot',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Si')]),
        ),
        migrations.DeleteModel(
            name='Cgi',
        ),
    ]
