# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0038_auto_20170617_1715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icg',
            old_name='icg_mg',
            new_name='icg_me',
        ),
        migrations.RenameField(
            model_name='icg',
            old_name='quien_mg',
            new_name='quien_me',
        ),
    ]
