# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0040_auto_20170617_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plutchik_s',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='plutchik_v',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='satisfaccion',
            name='identificador',
        ),
        migrations.DeleteModel(
            name='Plutchik_s',
        ),
        migrations.DeleteModel(
            name='Plutchik_v',
        ),
        migrations.DeleteModel(
            name='Satisfaccion',
        ),
    ]
