# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-17 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0041_auto_20170617_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='mg/dia'),
        ),
    ]
