# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-18 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0042_auto_20170617_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificador',
            name='psiquiatra',
            field=models.CharField(blank=True, choices=[(b'AKG', b'A. Keymer'), (b'AMB', b'A. Martin'), (b'SVC', b'S. Vieira')], max_length=3, verbose_name=b'psiquiatra'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='laboral',
            field=models.CharField(blank=True, choices=[(b'1', b'Activo'), (b'2', b'Baja temporal'), (b'3', b'Sin trabajo actual'), (b'4', b'Pensionista'), (b'5', b'Nunca ha trabajado'), (b'6', b'Estudiante'), (b'9', b'Desconocido')], max_length=1, verbose_name=b'Situaci\xc3\xb3n laboral'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'N\xc3\xbamero de hijos'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='procedencia',
            field=models.CharField(blank=True, choices=[(b'00', b'Urgencias'), (b'01', b'Sala B2'), (b'02', b'CSMA'), (b'03', b'H de d\xc3\xada'), (b'04', b'CCEE'), (b'05', b'Subagudos'), (b'99', b'Otros')], max_length=2, verbose_name=b'Procedencia'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='sector',
            field=models.CharField(blank=True, choices=[(b'1', b'AIS Gracia'), (b'2', b'AIS Dreta'), (b'3', b'AIS Guinard\xc3\xb3')], max_length=1, verbose_name=b'Sector'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='f_termino',
            field=models.DateField(blank=True, null=True, verbose_name=b'Fecha de t\xc3\xa9rmino'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='motivo',
            field=models.CharField(blank=True, choices=[(b'01', b'Abandono de tratamiento'), (b'02', b'Falta de eficacia'), (b'03', b'Efecto adverso EP'), (b'04', b'Efecto adverso digestivo'), (b'05', b'Efecto adverso hematologico'), (b'06', b'Efecto adverso auton\xc3\xb3mico'), (b'07', b'Otro efecto adverso'), (b'99', b'NE')], max_length=2, null=True),
        ),
    ]
