# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0052_auto_20170711_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who_das',
            name='d1_1',
            field=models.IntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede'), (None, b'N/A')], null=True, verbose_name=b'D1.1 '),
        ),
    ]
