# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0053_auto_20170712_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='who_das',
            name='d1_1',
            field=models.IntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ninguna'), (2, b'2.Leve'), (3, b'3.Moderada'), (4, b'4.Severa'), (5, b'5.Extrema / no puede')], null=True),
        ),
    ]
