# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0054_auto_20170712_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcis',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
    ]
