# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0055_auto_20170712_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcis',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Nada de acuerdo'), (1, b'1.Un poco de acuerdo'), (2, b'2.Bastante de acuerdo'), (3, b'3.Totalmente de acuerdo')], null=True),
        ),
    ]
