# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0056_auto_20170712_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bprs',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_16',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_17',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_18',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Muy leve'), (2, b'2.Leve'), (3, b'3.Moderado'), (4, b'4.Bastante acentuado'), (5, b'5.Grave'), (6, b'6.Muy Grave')], null=True),
        ),
    ]
