# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0057_auto_20170712_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csq8',
            name='autor',
            field=models.CharField(blank=True, choices=[(b'PAC', b'Paciente'), (b'FAM', b'Familia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'Excelente'), (b'3', b'Buen'), (b'2', b'Regula'), (b'1', b'Mala')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'No definitivamente'), (b'3', b'En muy pocos casos'), (b'2', b'Si en general'), (b'1', b'Si definitivamente')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'En casi todos'), (b'3', b'En la mayor parte'), (b'2', b'Solo en algunos'), (b'1', b'En ninguno')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'No definitivamente'), (b'3', b'No , creo que no'), (b'2', b'Si, creo que si'), (b'1', b'Si definitivamente')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'Nada satisfecho/a'), (b'3', b'Indiferente o moderadamente no satisfecho/a'), (b'2', b'Moderadamente satisfecho/a'), (b'1', b'Muy satisfecho/a')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'Si me ayudaron mucho'), (b'3', b'Si me ayudaron algo'), (b'2', b'No realmente no me ayudaron'), (b'1', b'No parec\xc3\xadan poner las cosas peor')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'Muy satisfecho/a'), (b'3', b'Moderadamente satisfecho/a'), (b'2', b'Algo insatisfecho/a'), (b'1', b'Muy Insatisfecho/a')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(b'4', b'No definitivamente'), (b'3', b'No posiblemente'), (b'2', b'Si, creo que si'), (b'1', b'Si con seguridad')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1. Mucho menos de lo que deseo'), (2, b'2. Menos de lo que deseo'), (3, b'3. Ni mucho ni poco'), (4, b'4. Casi como deseo'), (5, b'5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='icg_ge',
            name='icg_ge',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No evaluado'), (1, b'1.Normal, no enfermo'), (2, b'2.Dudosamente enfermo'), (3, b'3.Levemente enfermo'), (4, b'4.Moderadamente enfermo'), (5, b'5.Marcadamente enfermo'), (6, b'6.Gravemente enfermo'), (7, b'7.Entre los pac. mas extremadamente enfermos')], null=True),
        ),
        migrations.AlterField(
            model_name='icg_ge',
            name='quien_ge',
            field=models.CharField(choices=[(b'PSQ', b'Psiquiatra'), (b'PAC', b'Paciente')], max_length=3, null=True),
        ),
    ]
