# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0058_auto_20170712_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Estas sensaciones se indican solamente al ser preguntado'), (2, b'2.Estas sensaciones se relatan oral y espont\xc3\xa1neamente'), (3, b'3.Sensaciones no comunicadas verbalmente, es decir, por la expresi\xc3\xb3n facial, la postura, la voz y la tendencia al llanto'), (4, b'4.El paciente manifiesta estas sensaciones en su comunicaci\xc3\xb3n verbal y no verbal de forma espont\xc3\xa1nea')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Se culpa a si mismos, cree haber decepcionado a la gente'), (2, b'2.Ideas de culpabilidad, o meditaci\xc3\xb3n sobre errores pasados o malas acciones'), (3, b'3.La enfermedad actual es un castigo. Ideas delirantes de culpabilidad'), (4, b'4.Oye  voces  acusatorias  o  de  denuncia  y/o  experiemtna  alucinaciones  visuales amenazadoras')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Le parece que la vida no merece la pena ser vivida'), (2, b'2.Desear\xc3\xada estar muerto o tiene pensamientos sobre la posibilidad de morirse'), (3, b'3.Ideas de suicidio o amenazas'), (4, b'4.Intentos de suicidio (cualuqier intento serio se califica 4)')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Dificultades ocasionales para dormirse, por ejemplo, m\xc3\xa1s de media hora'), (2, b'2.Dificultades para dormirse cada noche')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.El paciente s queja de estar inquieto durante la noche'), (2, b'2.Est\xc3\xa1 despierto durante la noche; medicaci\xc3\xb3n, etc.')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Se despierta a primeras horas de la madrugada pero vuelve a dormirse'), (2, b'2.No puede volver a dormirse si se levanta de la cama')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Ideas  y  sentimientos  de  incapacidad.  Fatiga  o  debilidad  relcionadas  con  su actividad,trabajo o aficiones'), (2, b'2.P\xc3\xa9rdida de inter\xc3\xa9s en su actividad, aficiones, o trabajo, ,anifestado directamete por el enfermo o indirectamente por desatenci\xc3\xb3n, indecisi\xc3\xb3n y vacilaci\xc3\xb3n'), (3, b'3.Disminuci\xc3\xb3n del tiempo dedicado a actividades o descenso en la productividad'), (4, b'4.Dej\xc3\xb3 de trabajar por la presente enfermedad')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Palabra y pensamiento normales'), (1, b'1.Ligero retras en el di\xc3\xa1logo'), (2, b'2.Evidente retraso en el di\xc3\xa1logo'), (3, b'3.Di\xc3\xa1logo dif\xc3\xadcil'), (4, b'4.Torpeza absoluta')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ninguna'), (1, b'1.\xe2\x80\x9cJuega\xe2\x80\x9d con sus manos, cabellos, etc.'), (2, b'2.Se retuerce las manos, se muerde las u\xc3\xb1as, los labios, se tira de los cabellos, etc.')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.No hay dificultad'), (1, b'1.Tensi\xc3\xb3n subjetiva e irritable'), (2, b'2.Preocupaci\xc3\xb3n por peque\xc3\xb1as cosas'), (3, b'3.Actitud aprensiva aparente en la expresi\xc3\xb3n o en el habla'), (4, b'4.Terrores expresados sin preguntarle')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Ligera'), (2, b'2.Moderada'), (3, b'3.Grave'), (4, b'4.Incapacitante')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ninguno'), (1, b'1.P\xc3\xa9rdida de apetito, pero come sin necesidad de que estimulen. Sensaci\xc3\xb3n de pesadez en el abdomen'), (2, b'2.Dificultad en comer si no se le insiste. Solicita o necesita laxantes o medicaci\xc3\xb3n intestinal para sus s\xc3\xadntomas gastrointestinales')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ninguno'), (1, b'1.Pesadez en las extremidades, espalda o cabeza. Dorsalgias, cefalalgias, algias musculares. P\xc3\xa9rdida de energ\xc3\xada y fatigabilidad'), (2, b'2.Cualquier s\xc3\xadntoma bien definido')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.D\xc3\xa9bil'), (2, b'2.Grave'), (3, b'3.Incapacitante')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.No la hay'), (1, b'1.Preocupado de s\xc3\xad mismo (corporalmente)'), (2, b'2.Preocupado por su sald'), (3, b'3.Se lamenta constantemente, solicita ayudas, etc.'), (4, b'4.Ideas delirantes hipocondr\xc3\xadacas')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_16',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.No hay p\xc3\xa9rdida de peso'), (1, b'1.Probable p\xc3\xa9rdida de peso asociada con la enfermedad actual'), (2, b'2.P\xc3\xa9rdida de peso definida (seg\xc3\xban el enfermo)')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_17',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Se da cuenta de que est\xc3\xa1 deprimido y enfermo'), (1, b'1.Se da cuenta de sy enfermedad pero atribuye la causa a la mala alimentaci\xc3\xb3n, clima, exceso de trabajo, virus, etc.'), (2, b'2.Niega que est\xc3\xa9 enfermo')], null=True),
        ),
        migrations.AlterField(
            model_name='icg_me',
            name='icg_me',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No evaluado'), (1, b'1.Mucho mejor'), (2, b'2.Moderadamente mejor'), (3, b'3.Levemente mejor'), (4, b'4.Sin cambios'), (5, b'5.Levemente peor'), (6, b'6.Moderadamente peor'), (7, b'7.Mucho peor')], null=True),
        ),
        migrations.AlterField(
            model_name='icg_me',
            name='quien_me',
            field=models.CharField(choices=[(b'PSQ', b'Psiquiatra'), (b'PAC', b'Paciente')], max_length=3, null=True),
        ),
    ]
