# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0059_auto_20170712_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Sin tristeza'), (1, b'1.'), (2, b'2. Parece deca\xc3\xaddo/a pero se anima sin dificultad'), (3, b'3.'), (4, b'4. Parece triste y desgraciado/a la mayor parte del tiempo'), (5, b'5.'), (6, b'6.Parece siempre desgraciado/a. Extremadamente abatido/a')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Tristeza espor\xc3\xa1dica seg\xc3\xban las circunstancias'), (1, b'1.'), (2, b'2. Triste o deca\xc3\xaddo/a, pero se anima sin dificultad'), (3, b'3.'), (4, b'4. Sentimientos generalizados de tristeza o melancol\xc3\xada. El estado de \xc3\xa1nimo todav\xc3\xada se ve influido por circunstancias externas'), (5, b'5.'), (6, b'6. Abatimiento, desdicha o tristeza continuada o invariable')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Apacible. S\xc3\xb3lo tensi\xc3\xb3n interna pasajera'), (1, b'1.'), (2, b'2. Sentimientos ocacionales de nerviosismo y maletar indefinido'), (3, b'3.'), (4, b'4. Sentimientos continuados de tensi\xc3\xb3n interna o p\xc3\xa1nico intermitente que el sujeto s\xc3\xb3lo puede dominar con alguna dificultad'), (5, b'5.'), (6, b'6. Terror o angustia tenaz. P\xc3\xa1nico irresistible')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Duerme como siempre'), (1, b'1.'), (2, b'2. Ligera dificultad para dormirse o sue\xc3\xb1o ligeramente reducido, sue\xc3\xb1o ligero o perturbado'), (3, b'3.'), (4, b'4. Sue\xc3\xb1o reducido o interrumpido durante al menos 2 h'), (5, b'5.'), (6, b'6. Menos de 2 o 3 h de sue\xc3\xb1o')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Apetito normal o aumentado'), (1, b'1.'), (2, b'2. Apetito ligeramente reducido'), (3, b'3.'), (4, b'4. Sin apetito. La comida es ins\xc3\xadpida'), (5, b'5.'), (6, b'6. Necesita persuasi\xc3\xb3n para comer algo')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Ninguna dificultad para concentrarse'), (1, b'1.'), (2, b'2. Dificultades ocasionales para centrar los pensamientos'), (3, b'3.'), (4, b'4. Dificultades para concentrarse y seguir una idea que reduce la capacidad de leer o mantener una conversaci\xc3\xb3n'), (5, b'5.'), (6, b'6. Incapaz de leer o mantener una conversaci\xc3\xb3n si no es con gran dificultad')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Casi sin dificultad para empezar algo. Sin apat\xc3\xada'), (1, b'1.'), (2, b'2. Dificultades para empezar actividades'), (3, b'3.'), (4, b'4. Dificultades para empezar actividades rutinarias sencillas que se llevan a cabo con esfuerzo'), (5, b'5.'), (6, b'6. Lasitud total. Incapaz de hacer nada sin ayuda')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Inter\xc3\xa9s normal por el entorno y por otras personas'), (1, b'1.'), (2, b'2. Menor capacidad para disfrutar de las cosas que normalmen te le interesan'), (3, b'3.'), (4, b'4. P\xc3\xa9rdida de inter\xc3\xa9s por el entorno. P\xc3\xa9rdida de sentimientos respecto a los amigos y conocidos'), (5, b'5.'), (6, b'6. La experiencia de estar emocionalmente paralizado, incapacidad para sentir enfado, pena o placer y una total o incluso dolorosa falta de sentimientos hacia los parientes pr\xc3\xb3ximos y amigos')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Sin pensamientos pesimistas'), (1, b'1.'), (2, b'2. Ideas variables de fracaso, autorreproche o autodesprecio'), (3, b'3.'), (4, b'4. Autoacusaciones persistentes o ideas definidas, pero a\xc3\xban racionales, de culpabilidad o pecado. Cada vez m\xc3\xa1s pesimista respecto al futuro'), (5, b'5.'), (6, b'6. Alucinaciones de ruina, remordimiento o pecado irredimible. Autoacusaciones que son absurdas e inquebrantables')], null=True),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Disfruta de la vida o la acepta tal como viene'), (1, b'1.'), (2, b'2. Cansado de vivir. S\xc3\xb3lo pensamientos suicidas pasajeros'), (3, b'3.'), (4, b'4. Probablemente  estar\xc3\xada  mejor  muerto/a. Los  pensamientos suicidas son habituales, y se considera el suicidio como una posible soluci\xc3\xb3n, pero sin ninguna intenci\xc3\xb3n o plan espec\xc3\xadfico'), (5, b'5.'), (6, b'6. Planes expl\xc3\xadcitos de suicidio cuando se presente una oportunidad. Preparativos activos para el suicidio')], null=True),
        ),
    ]
