# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0060_auto_20170712_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panss',
            name='item_g01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g16',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Posible o moderada, s\xc3\xb3lo cuando se le pregunta'), (2, b'2.Clara aunque subjetiva y apropiada al contenido: optimista, seguro de s\xc3\xad mismo/a, alegre'), (3, b'3.Elevada e inapropiada'), (4, b'4.Claramente euf\xc3\xb3rico/a, risa inadecuada, canta durante la entrevista, etc.')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.Subjetivamente aumentada'), (2, b'2.Vigoroso/a, hipergestual'), (3, b'3.Energ\xc3\xada excesiva, hiperactividad fluctuante, inquietud (puede ser calmado/a)'), (4, b'4.Agitaci\xc3\xb3n o hiperactividad constante (no puede ser calmado/a)')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Normal, no aumentado'), (1, b'1.Posible o moderadamente aumentado'), (2, b'2.Claro aumento al preguntar'), (3, b'3.Referido como elevado de forma espont\xc3\xa1nea, contenido sexual del discurso, preocupaci\xc3\xb3n por temas sexuales'), (4, b'4.Actos o incitaciones sexuales evidentes (hacia pacientes, personal o entrevistador)')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.No reducido'), (1, b'1.Disminuci\xc3\xb3n en menos de 1 ,hora'), (2, b'2.Disminuci\xc3\xb3n en m\xc3\xa1s de 1 hora'), (3, b'3.Refiere disminuci\xc3\xb3n de la necesidad de dormir'), (4, b'4.Niega necesidad de dormir')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente'), (1, b'1.'), (2, b'2.Subjetivamente aumentada'), (3, b'3.'), (4, b'4.Irritabilidad fluctuante durante la entrevista, episodios recientes de rabia o enfado'), (5, b'5.'), (6, b'6.Predominantemente irritable durante la entrevista, brusco y cortante'), (7, b'7.'), (8, b'8.Hostil, no colaborador/a, entrevista imposible')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.No aumentada'), (1, b'1.'), (2, b'2.Sensaci\xc3\xb3n de locuacidad'), (3, b'3.'), (4, b'4.Aumentada de forma fluctuante, verborrea ocasional'), (5, b'5.'), (6, b'6.Claramente aumentada en ritmo y cantidad, dif\xc3\xadcil de interrumpir, intrusiva'), (7, b'7.'), (8, b'8.Verborrea ininterrumpible y continua')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausentes'), (1, b'1.Circunstancialidad, distraibilidad moderada, aceleraci\xc3\xb3n del pensamiento'), (2, b'2.Distraibilidad clara, descarrilamiento, taquipsiquia'), (3, b'3.Fuga de ideas, tangencialidad, discurso dif\xc3\xadcil de seguir, rimas, ecolalia'), (4, b'4.Incoherencia, ininteligibilidad, comunicaci\xc3\xb3n imposible')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausentes'), (1, b'1.'), (2, b'2.Planes discutibles, nuevos intereses'), (3, b'3.'), (4, b'4.Proyectos especiales, misticismo'), (5, b'5.'), (6, b'6.Ideas grandiosas o paranoides, ideas de referencia'), (7, b'7.'), (8, b'8.Delirios, alucinaciones')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Ausente, colaborador/a'), (1, b'1.'), (2, b'2.Sarc\xc3\xa1stico/a, enf\xc3\xa1tico/a, lac\xc3\xb3nico/a'), (3, b'3.'), (4, b'4.Querulante, pone en guardia'), (5, b'5.'), (6, b'6.Amenaza al entrevistador, habla a gritos, entrevista dif\xc3\xadcil'), (7, b'7.'), (8, b'8.Claramente agresivo/a, destructivo/a, entrevista imposible')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Higiene e indumentaria apropiada '), (1, b'1.Ligeramente descuidada'), (2, b'2.Mal arreglado/a, moderadamente despeinado/a, indumentaria sobrecargada'), (3, b'3.Despeinado/a, semidesnudo/a, maquillaje llamativo'), (4, b'4.Completamente desaseado/a, adornado/a, indumentaria extravagante')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0.Presente, admite la enfermedad, acepta tratamiento'), (1, b'1.Seg\xc3\xban \xc3\xa9l/ella, posiblemente enfermo/a'), (2, b'2.Admite cambio de conducta, pero niega enfermedad'), (3, b'3.Admite posible cambio de conducta, niega enfermedad'), (4, b'4.Niega cualquier cambio de conduct')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_16',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_17',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_18',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_19',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_20',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_21',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_22',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, b'0. Nunca'), (1, b'1. Casi nunca'), (2, b'2. A veces'), (3, b'3. Bastantes veces'), (4, b'4. Siempre')], null=True),
        ),
    ]
