# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0062_auto_20170712_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Estas sensaciones se indican solamente al ser preguntado'), (2, b'2.Estas sensaciones se relatan oral y espont\xc3\xa1neamente'), (3, b'3.Sensaciones no comunicadas verbalmente, es decir, por la expresi\xc3\xb3n facial, la postura, la voz y la tendencia al llanto'), (4, b'4.El paciente manifiesta estas sensaciones en su comunicaci\xc3\xb3n verbal y no verbal de forma espont\xc3\xa1nea')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Se culpa a si mismos, cree haber decepcionado a la gente'), (2, b'2.Ideas de culpabilidad, o meditaci\xc3\xb3n sobre errores pasados o malas acciones'), (3, b'3.La enfermedad actual es un castigo. Ideas delirantes de culpabilidad'), (4, b'4.Oye  voces  acusatorias  o  de  denuncia  y/o  experiemtna  alucinaciones  visuales amenazadoras')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Le parece que la vida no merece la pena ser vivida'), (2, b'2.Desear\xc3\xada estar muerto o tiene pensamientos sobre la posibilidad de morirse'), (3, b'3.Ideas de suicidio o amenazas'), (4, b'4.Intentos de suicidio (cualuqier intento serio se califica 4)')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Dificultades ocasionales para dormirse, por ejemplo, m\xc3\xa1s de media hora'), (2, b'2.Dificultades para dormirse cada noche')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.El paciente s queja de estar inquieto durante la noche'), (2, b'2.Est\xc3\xa1 despierto durante la noche; medicaci\xc3\xb3n, etc.')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Se despierta a primeras horas de la madrugada pero vuelve a dormirse'), (2, b'2.No puede volver a dormirse si se levanta de la cama')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Ideas  y  sentimientos  de  incapacidad.  Fatiga  o  debilidad  relcionadas  con  su actividad,trabajo o aficiones'), (2, b'2.P\xc3\xa9rdida de inter\xc3\xa9s en su actividad, aficiones, o trabajo, ,anifestado directamete por el enfermo o indirectamente por desatenci\xc3\xb3n, indecisi\xc3\xb3n y vacilaci\xc3\xb3n'), (3, b'3.Disminuci\xc3\xb3n del tiempo dedicado a actividades o descenso en la productividad'), (4, b'4.Dej\xc3\xb3 de trabajar por la presente enfermedad')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Palabra y pensamiento normales'), (1, b'1.Ligero retras en el di\xc3\xa1logo'), (2, b'2.Evidente retraso en el di\xc3\xa1logo'), (3, b'3.Di\xc3\xa1logo dif\xc3\xadcil'), (4, b'4.Torpeza absoluta')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ninguna'), (1, b'1.\xe2\x80\x9cJuega\xe2\x80\x9d con sus manos, cabellos, etc.'), (2, b'2.Se retuerce las manos, se muerde las u\xc3\xb1as, los labios, se tira de los cabellos, etc.')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No hay dificultad'), (1, b'1.Tensi\xc3\xb3n subjetiva e irritable'), (2, b'2.Preocupaci\xc3\xb3n por peque\xc3\xb1as cosas'), (3, b'3.Actitud aprensiva aparente en la expresi\xc3\xb3n o en el habla'), (4, b'4.Terrores expresados sin preguntarle')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_11',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.Ligera'), (2, b'2.Moderada'), (3, b'3.Grave'), (4, b'4.Incapacitante')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_12',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ninguno'), (1, b'1.P\xc3\xa9rdida de apetito, pero come sin necesidad de que estimulen. Sensaci\xc3\xb3n de pesadez en el abdomen'), (2, b'2.Dificultad en comer si no se le insiste. Solicita o necesita laxantes o medicaci\xc3\xb3n intestinal para sus s\xc3\xadntomas gastrointestinales')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_13',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ninguno'), (1, b'1.Pesadez en las extremidades, espalda o cabeza. Dorsalgias, cefalalgias, algias musculares. P\xc3\xa9rdida de energ\xc3\xada y fatigabilidad'), (2, b'2.Cualquier s\xc3\xadntoma bien definido')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_14',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Ausente'), (1, b'1.D\xc3\xa9bil'), (2, b'2.Grave'), (3, b'3.Incapacitante')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_15',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No la hay'), (1, b'1.Preocupado de s\xc3\xad mismo (corporalmente)'), (2, b'2.Preocupado por su sald'), (3, b'3.Se lamenta constantemente, solicita ayudas, etc.'), (4, b'4.Ideas delirantes hipocondr\xc3\xadacas')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_16',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No hay p\xc3\xa9rdida de peso'), (1, b'1.Probable p\xc3\xa9rdida de peso asociada con la enfermedad actual'), (2, b'2.P\xc3\xa9rdida de peso definida (seg\xc3\xban el enfermo)')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_17',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.Se da cuenta de que est\xc3\xa1 deprimido y enfermo'), (1, b'1.Se da cuenta de sy enfermedad pero atribuye la causa a la mala alimentaci\xc3\xb3n, clima, exceso de trabajo, virus, etc.'), (2, b'2.Niega que est\xc3\xa9 enfermo')], default=0),
        ),
        migrations.AlterField(
            model_name='icg_ge',
            name='icg_ge',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No evaluado'), (1, b'1.Normal, no enfermo'), (2, b'2.Dudosamente enfermo'), (3, b'3.Levemente enfermo'), (4, b'4.Moderadamente enfermo'), (5, b'5.Marcadamente enfermo'), (6, b'6.Gravemente enfermo'), (7, b'7.Entre los pac. mas extremadamente enfermos')], default=0),
        ),
        migrations.AlterField(
            model_name='icg_ge',
            name='quien_ge',
            field=models.CharField(choices=[(b'PSQ', b'Psiquiatra'), (b'PAC', b'Paciente')], default=b'PSQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='icg_me',
            name='icg_me',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0.No evaluado'), (1, b'1.Mucho mejor'), (2, b'2.Moderadamente mejor'), (3, b'3.Levemente mejor'), (4, b'4.Sin cambios'), (5, b'5.Levemente peor'), (6, b'6.Moderadamente peor'), (7, b'7.Mucho peor')], default=0),
        ),
        migrations.AlterField(
            model_name='icg_me',
            name='quien_me',
            field=models.CharField(choices=[(b'PSQ', b'Psiquiatra'), (b'PAC', b'Paciente')], default=b'PSQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Sin tristeza'), (1, b'1.'), (2, b'2. Parece deca\xc3\xaddo/a pero se anima sin dificultad'), (3, b'3.'), (4, b'4. Parece triste y desgraciado/a la mayor parte del tiempo'), (5, b'5.'), (6, b'6.Parece siempre desgraciado/a. Extremadamente abatido/a')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Tristeza espor\xc3\xa1dica seg\xc3\xban las circunstancias'), (1, b'1.'), (2, b'2. Triste o deca\xc3\xaddo/a, pero se anima sin dificultad'), (3, b'3.'), (4, b'4. Sentimientos generalizados de tristeza o melancol\xc3\xada. El estado de \xc3\xa1nimo todav\xc3\xada se ve influido por circunstancias externas'), (5, b'5.'), (6, b'6. Abatimiento, desdicha o tristeza continuada o invariable')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Apacible. S\xc3\xb3lo tensi\xc3\xb3n interna pasajera'), (1, b'1.'), (2, b'2. Sentimientos ocacionales de nerviosismo y maletar indefinido'), (3, b'3.'), (4, b'4. Sentimientos continuados de tensi\xc3\xb3n interna o p\xc3\xa1nico intermitente que el sujeto s\xc3\xb3lo puede dominar con alguna dificultad'), (5, b'5.'), (6, b'6. Terror o angustia tenaz. P\xc3\xa1nico irresistible')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Duerme como siempre'), (1, b'1.'), (2, b'2. Ligera dificultad para dormirse o sue\xc3\xb1o ligeramente reducido, sue\xc3\xb1o ligero o perturbado'), (3, b'3.'), (4, b'4. Sue\xc3\xb1o reducido o interrumpido durante al menos 2 h'), (5, b'5.'), (6, b'6. Menos de 2 o 3 h de sue\xc3\xb1o')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Apetito normal o aumentado'), (1, b'1.'), (2, b'2. Apetito ligeramente reducido'), (3, b'3.'), (4, b'4. Sin apetito. La comida es ins\xc3\xadpida'), (5, b'5.'), (6, b'6. Necesita persuasi\xc3\xb3n para comer algo')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Ninguna dificultad para concentrarse'), (1, b'1.'), (2, b'2. Dificultades ocasionales para centrar los pensamientos'), (3, b'3.'), (4, b'4. Dificultades para concentrarse y seguir una idea que reduce la capacidad de leer o mantener una conversaci\xc3\xb3n'), (5, b'5.'), (6, b'6. Incapaz de leer o mantener una conversaci\xc3\xb3n si no es con gran dificultad')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Casi sin dificultad para empezar algo. Sin apat\xc3\xada'), (1, b'1.'), (2, b'2. Dificultades para empezar actividades'), (3, b'3.'), (4, b'4. Dificultades para empezar actividades rutinarias sencillas que se llevan a cabo con esfuerzo'), (5, b'5.'), (6, b'6. Lasitud total. Incapaz de hacer nada sin ayuda')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Inter\xc3\xa9s normal por el entorno y por otras personas'), (1, b'1.'), (2, b'2. Menor capacidad para disfrutar de las cosas que normalmen te le interesan'), (3, b'3.'), (4, b'4. P\xc3\xa9rdida de inter\xc3\xa9s por el entorno. P\xc3\xa9rdida de sentimientos respecto a los amigos y conocidos'), (5, b'5.'), (6, b'6. La experiencia de estar emocionalmente paralizado, incapacidad para sentir enfado, pena o placer y una total o incluso dolorosa falta de sentimientos hacia los parientes pr\xc3\xb3ximos y amigos')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Sin pensamientos pesimistas'), (1, b'1.'), (2, b'2. Ideas variables de fracaso, autorreproche o autodesprecio'), (3, b'3.'), (4, b'4. Autoacusaciones persistentes o ideas definidas, pero a\xc3\xban racionales, de culpabilidad o pecado. Cada vez m\xc3\xa1s pesimista respecto al futuro'), (5, b'5.'), (6, b'6. Alucinaciones de ruina, remordimiento o pecado irredimible. Autoacusaciones que son absurdas e inquebrantables')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(choices=[(0, b'0. Disfruta de la vida o la acepta tal como viene'), (1, b'1.'), (2, b'2. Cansado de vivir. S\xc3\xb3lo pensamientos suicidas pasajeros'), (3, b'3.'), (4, b'4. Probablemente  estar\xc3\xada  mejor  muerto/a. Los  pensamientos suicidas son habituales, y se considera el suicidio como una posible soluci\xc3\xb3n, pero sin ninguna intenci\xc3\xb3n o plan espec\xc3\xadfico'), (5, b'5.'), (6, b'6. Planes expl\xc3\xadcitos de suicidio cuando se presente una oportunidad. Preparativos activos para el suicidio')], default=0),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g01',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g02',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g03',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g04',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g05',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g06',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g07',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g08',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g09',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g10',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g11',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g12',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g13',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g14',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g15',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g16',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n01',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n02',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n03',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n04',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n05',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n06',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n07',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p01',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p02',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p03',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p04',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p05',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p06',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p07',
            field=models.PositiveSmallIntegerField(choices=[(1, b'1.Ausente'), (2, b'2.M\xc3\xadnimo'), (3, b'3.Ligero'), (4, b'4.Moderado'), (5, b'5.Moderado severo'), (6, b'6.Severo'), (7, b'7.Extremo')], default=1),
        ),
    ]
