# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0064_auto_20170713_0634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Satis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, choices=[(b'PAC', b'Paciente'), (b'FAM', b'Familia')], max_length=3)),
                ('item_01', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_02', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_03', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_04', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_05', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_06', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_07', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_08', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_09', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Muy Poca'), (2, b'2.Poca'), (3, b'3.Normal'), (4, b'4.Bastante'), (5, b'5.Mucha')], null=True)),
                ('item_10', models.PositiveSmallIntegerField(blank=True, choices=[(1, b'1.Siempre ingresaria en hosp'), (2, b'2.Casi siempre hosp '), (3, b'3.Me dar\xc3\xada igual'), (4, b'4.Casi siempre dom'), (5, b'5.Siempre dom')], null=True)),
            ],
            options={
                'verbose_name': 'Satisfaccion',
                'verbose_name_plural': 'Escalas Satisfaccion',
            },
        ),
    ]
