# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0065_satis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csq8',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'Excelente'), (3, b'Buen'), (2, b'Regula'), (1, b'Mala')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'No definitivamente'), (3, b'En muy pocos casos'), (2, b'Si en general'), (1, b'Si definitivamente')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'En casi todos'), (3, b'En la mayor parte'), (2, b'Solo en algunos'), (1, b'En ninguno')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'No definitivamente'), (3, b'No , creo que no'), (2, b'Si, creo que si'), (1, b'Si definitivamente')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'Nada satisfecho/a'), (3, b'Indiferente o moderadamente no satisfecho/a'), (2, b'Moderadamente satisfecho/a'), (1, b'Muy satisfecho/a')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'Si me ayudaron mucho'), (3, b'Si me ayudaron algo'), (2, b'No realmente no me ayudaron'), (1, b'No parec\xc3\xadan poner las cosas peor')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'Muy satisfecho/a'), (3, b'Moderadamente satisfecho/a'), (2, b'Algo insatisfecho/a'), (1, b'Muy Insatisfecho/a')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, b'No definitivamente'), (3, b'No posiblemente'), (2, b'Si, creo que si'), (1, b'Si con seguridad')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_09',
            field=models.TextField(blank=True, null=True),
        ),
    ]
