# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0067_identificador_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico_pac',
            name='dg_previo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_previo', to='escalas.Diagnostico', verbose_name=b'Diagnostico previo'),
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='mg_dia_inicio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name=b'dosis inicio (mg/dia)'),
        ),
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_alta', to='escalas.Diagnostico', verbose_name=b'Diagnostico al alta'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name=b'dosis final (mg/dia)'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='motivo',
            field=models.CharField(blank=True, choices=[(b'01', b'Abandono de tratamiento'), (b'02', b'Falta de respuesta'), (b'03', b'Efecto adverso EP'), (b'04', b'Efecto adverso digestivo'), (b'05', b'Efecto adverso hematologico'), (b'06', b'Efecto adverso auton\xc3\xb3mico'), (b'07', b'Otro efecto adverso'), (b'08', b'Respuesta parcial'), (b'99', b'NE')], max_length=2, null=True),
        ),
    ]
