# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 12:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0068_auto_20170728_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico_pac',
            name='f_dg',
        ),
        migrations.RemoveField(
            model_name='tratamiento',
            name='f_inicio',
        ),
    ]
