# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-09 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0070_remove_tratamiento_f_termino'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico',
            name='dsm',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
