# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0071_diagnostico_dsm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='rechazo',
            field=models.CharField(blank=True, choices=[(b'01', b'Riesgo autol\xc3\xadtico'), (b'02', b'Falta de soporte familiar'), (b'03', b'Falta de voluntariedad'), (b'04', b'Sin criterio de ingreso agudo'), (b'05', b'No acude'), (b'99', b'Otros')], max_length=2, null=True, verbose_name=b'\xc2\xbfrechazo ingreso?'),
        ),
    ]
