# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0072_auto_20170830_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico_pac',
            name='dg_previo',
        ),
        migrations.AddField(
            model_name='diagnostico_pac',
            name='dg_tipo',
            field=models.CharField(choices=[(b'ant', b'Dg. Previo'), (b'ppl', b'Dg. Principal'), (b'sec', b'Dg. Secundario')], default='ppl', max_length=3),
            preserve_default=False,
        ),
    ]
