# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0073_auto_20171003_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='dg_tipo',
            field=models.CharField(choices=[(b'ant', b'Dg. Previo'), (b'ppl', b'Dg. Principal'), (b'sec', b'Dg. Secundario')], default=b'ppl', max_length=3),
        ),
    ]
