# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0075_identificador_estado_alta'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificador',
            name='calidad_cuidador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Calidad cuidador'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='claudica_cuidador',
            field=models.BooleanField(default=False, verbose_name=b'Soporta todo el ingreso?'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='cuidador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Cuidador'),
        ),
        migrations.AddField(
            model_name='identificador',
            name='horas_cuidador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name=b'Tiempo cuidador'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='estado_alta',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='rechazo',
            field=models.CharField(blank=True, choices=[(b'01', b'Riesgo autol\xc3\xadtico'), (b'02', b'Falta de soporte familiar'), (b'03', b'Falta de voluntariedad'), (b'04', b'Sin criterio de ingreso agudo'), (b'05', b'No acude'), (b'99', b'Otros')], help_text=b'S\xc3\xb3lo llenar si rechaza ingreso.', max_length=2, null=True, verbose_name=b'\xc2\xbfrechazo ingreso?'),
        ),
    ]
