# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0076_auto_20171003_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='claudica_cuidador',
            field=models.NullBooleanField(default=False, verbose_name=b'Claudica?'),
        ),
    ]
