# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0077_auto_20171003_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='claudica_cuidador',
            field=models.NullBooleanField(verbose_name=b'Claudica?'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='estado_alta',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
