# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0078_auto_20171003_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='claudica_cuidador',
            field=models.BooleanField(default=False),
        ),
    ]
