# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0079_auto_20171003_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico_pac',
            name='dg_tipo',
        ),
        migrations.AddField(
            model_name='diagnostico_pac',
            name='dg_ppal',
            field=models.BooleanField(default=False, verbose_name=b'Dg Principal'),
        ),
        migrations.AddField(
            model_name='diagnostico_pac',
            name='dg_previo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_previo', to='escalas.Diagnostico', verbose_name=b'Diagnostico previo'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='claudica_cuidador',
            field=models.BooleanField(default=False, verbose_name=b'\xc2\xbfClaudicacion familiar?'),
        ),
    ]
