# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0081_auto_20171004_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='dg_previo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_previo', to='escalas.Diagnostico', verbose_name=b'Diagnostico previo'),
        ),
    ]
