# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0081_auto_20171004_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostico_pac',
            name='dg_tipo',
        ),
        migrations.AddField(
            model_name='diagnostico_pac',
            name='dg_ppal',
            field=models.BooleanField(default=False, verbose_name=b'Dg Principal'),
        ),
    ]
