# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-04 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0082_auto_20171004_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='dg_principal',
            field=models.BooleanField(default=False, verbose_name=b'Dg Principal'),
        ),
    ]
