# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-14 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0083_auto_20171004_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bcis',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bcis',
            name='item_15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0.Nada de acuerdo'), (1, '1.Un poco de acuerdo'), (2, '2.Bastante de acuerdo'), (3, '3.Totalmente de acuerdo')], null=True),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_01',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_02',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_03',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_04',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_05',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_06',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_07',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_08',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_09',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_10',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_11',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_12',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_13',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_14',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_15',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_16',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_17',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='bprs',
            name='item_18',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Muy leve'), (2, '2.Leve'), (3, '3.Moderado'), (4, '4.Bastante acentuado'), (5, '5.Grave'), (6, '6.Muy Grave')], default=0),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='autor',
            field=models.CharField(blank=True, choices=[('PAC', 'Paciente'), ('FAM', 'Familia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Excelente'), (3, 'Buen'), (2, 'Regula'), (1, 'Mala')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'No definitivamente'), (3, 'En muy pocos casos'), (2, 'Si en general'), (1, 'Si definitivamente')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'En casi todos'), (3, 'En la mayor parte'), (2, 'Solo en algunos'), (1, 'En ninguno')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'No definitivamente'), (3, 'No , creo que no'), (2, 'Si, creo que si'), (1, 'Si definitivamente')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Nada satisfecho/a'), (3, 'Indiferente o moderadamente no satisfecho/a'), (2, 'Moderadamente satisfecho/a'), (1, 'Muy satisfecho/a')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Si me ayudaron mucho'), (3, 'Si me ayudaron algo'), (2, 'No realmente no me ayudaron'), (1, 'No parecían poner las cosas peor')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Muy satisfecho/a'), (3, 'Moderadamente satisfecho/a'), (2, 'Algo insatisfecho/a'), (1, 'Muy Insatisfecho/a')], null=True),
        ),
        migrations.AlterField(
            model_name='csq8',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'No definitivamente'), (3, 'No posiblemente'), (2, 'Si, creo que si'), (1, 'Si con seguridad')], null=True),
        ),
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='dg_previo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dg_previo', to='escalas.Diagnostico', verbose_name='Diagnostico previo'),
        ),
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='dg_principal',
            field=models.BooleanField(default=False, verbose_name='Dg Principal'),
        ),
        migrations.AlterField(
            model_name='diagnostico_pac',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dg_alta', to='escalas.Diagnostico', verbose_name='Diagnostico al alta'),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='duke',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1. Mucho menos de lo que deseo'), (2, '2. Menos de lo que deseo'), (3, '3. Ni mucho ni poco'), (4, '4. Casi como deseo'), (5, '5. Tanto como deseo')], null=True),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Estas sensaciones se indican solamente al ser preguntado'), (2, '2.Estas sensaciones se relatan oral y espontáneamente'), (3, '3.Sensaciones no comunicadas verbalmente, es decir, por la expresión facial, la postura, la voz y la tendencia al llanto'), (4, '4.El paciente manifiesta estas sensaciones en su comunicación verbal y no verbal de forma espontánea')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Se culpa a si mismos, cree haber decepcionado a la gente'), (2, '2.Ideas de culpabilidad, o meditación sobre errores pasados o malas acciones'), (3, '3.La enfermedad actual es un castigo. Ideas delirantes de culpabilidad'), (4, '4.Oye  voces  acusatorias  o  de  denuncia  y/o  experiemtna  alucinaciones  visuales amenazadoras')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Le parece que la vida no merece la pena ser vivida'), (2, '2.Desearía estar muerto o tiene pensamientos sobre la posibilidad de morirse'), (3, '3.Ideas de suicidio o amenazas'), (4, '4.Intentos de suicidio (cualuqier intento serio se califica 4)')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Dificultades ocasionales para dormirse, por ejemplo, más de media hora'), (2, '2.Dificultades para dormirse cada noche')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.El paciente s queja de estar inquieto durante la noche'), (2, '2.Está despierto durante la noche; medicación, etc.')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Se despierta a primeras horas de la madrugada pero vuelve a dormirse'), (2, '2.No puede volver a dormirse si se levanta de la cama')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Ideas  y  sentimientos  de  incapacidad.  Fatiga  o  debilidad  relcionadas  con  su actividad,trabajo o aficiones'), (2, '2.Pérdida de interés en su actividad, aficiones, o trabajo, ,anifestado directamete por el enfermo o indirectamente por desatención, indecisión y vacilación'), (3, '3.Disminución del tiempo dedicado a actividades o descenso en la productividad'), (4, '4.Dejó de trabajar por la presente enfermedad')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Palabra y pensamiento normales'), (1, '1.Ligero retras en el diálogo'), (2, '2.Evidente retraso en el diálogo'), (3, '3.Diálogo difícil'), (4, '4.Torpeza absoluta')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ninguna'), (1, '1.“Juega” con sus manos, cabellos, etc.'), (2, '2.Se retuerce las manos, se muerde las uñas, los labios, se tira de los cabellos, etc.')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No hay dificultad'), (1, '1.Tensión subjetiva e irritable'), (2, '2.Preocupación por pequeñas cosas'), (3, '3.Actitud aprensiva aparente en la expresión o en el habla'), (4, '4.Terrores expresados sin preguntarle')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_11',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Ligera'), (2, '2.Moderada'), (3, '3.Grave'), (4, '4.Incapacitante')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_12',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ninguno'), (1, '1.Pérdida de apetito, pero come sin necesidad de que estimulen. Sensación de pesadez en el abdomen'), (2, '2.Dificultad en comer si no se le insiste. Solicita o necesita laxantes o medicación intestinal para sus síntomas gastrointestinales')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_13',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ninguno'), (1, '1.Pesadez en las extremidades, espalda o cabeza. Dorsalgias, cefalalgias, algias musculares. Pérdida de energía y fatigabilidad'), (2, '2.Cualquier síntoma bien definido')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_14',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Débil'), (2, '2.Grave'), (3, '3.Incapacitante')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_15',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No la hay'), (1, '1.Preocupado de sí mismo (corporalmente)'), (2, '2.Preocupado por su sald'), (3, '3.Se lamenta constantemente, solicita ayudas, etc.'), (4, '4.Ideas delirantes hipocondríacas')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_16',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No hay pérdida de peso'), (1, '1.Probable pérdida de peso asociada con la enfermedad actual'), (2, '2.Pérdida de peso definida (según el enfermo)')], default=0),
        ),
        migrations.AlterField(
            model_name='hdrs',
            name='item_17',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Se da cuenta de que está deprimido y enfermo'), (1, '1.Se da cuenta de sy enfermedad pero atribuye la causa a la mala alimentación, clima, exceso de trabajo, virus, etc.'), (2, '2.Niega que esté enfermo')], default=0),
        ),
        migrations.AlterField(
            model_name='icg_ge',
            name='icg_ge',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No evaluado'), (1, '1.Normal, no enfermo'), (2, '2.Dudosamente enfermo'), (3, '3.Levemente enfermo'), (4, '4.Moderadamente enfermo'), (5, '5.Marcadamente enfermo'), (6, '6.Gravemente enfermo'), (7, '7.Entre los pac. mas extremadamente enfermos')], default=0),
        ),
        migrations.AlterField(
            model_name='icg_ge',
            name='quien_ge',
            field=models.CharField(choices=[('PSQ', 'Psiquiatra'), ('PAC', 'Paciente')], default='PSQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='icg_me',
            name='icg_me',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No evaluado'), (1, '1.Mucho mejor'), (2, '2.Moderadamente mejor'), (3, '3.Levemente mejor'), (4, '4.Sin cambios'), (5, '5.Levemente peor'), (6, '6.Moderadamente peor'), (7, '7.Mucho peor')], default=0),
        ),
        migrations.AlterField(
            model_name='icg_me',
            name='quien_me',
            field=models.CharField(choices=[('PSQ', 'Psiquiatra'), ('PAC', 'Paciente')], default='PSQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='calidad_cuidador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Calidad cuidador'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='claudica_cuidador',
            field=models.BooleanField(default=False, verbose_name='¿Claudicacion familiar?'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='cuidador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cuidador'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='horas_cuidador',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tiempo cuidador'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='laboral',
            field=models.CharField(blank=True, choices=[('1', 'Activo'), ('2', 'Baja temporal'), ('3', 'Sin trabajo actual'), ('4', 'Pensionista'), ('5', 'Nunca ha trabajado'), ('6', 'Estudiante'), ('9', 'Desconocido')], max_length=1, verbose_name='Situación laboral'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='n_hijos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número de hijos'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('00', 'Urgencias'), ('01', 'Sala B2'), ('02', 'CSMA'), ('03', 'H de día'), ('04', 'CCEE'), ('05', 'Subagudos'), ('99', 'Otros')], max_length=2, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='psiquiatra',
            field=models.CharField(blank=True, choices=[('AKG', 'A. Keymer'), ('AMB', 'A. Martin'), ('SVC', 'S. Vieira')], max_length=3, verbose_name='psiquiatra'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='rechazo',
            field=models.CharField(blank=True, choices=[('01', 'Riesgo autolítico'), ('02', 'Falta de soporte familiar'), ('03', 'Falta de voluntariedad'), ('04', 'Sin criterio de ingreso agudo'), ('05', 'No acude'), ('99', 'Otros')], help_text='Sólo llenar si rechaza ingreso.', max_length=2, null=True, verbose_name='¿rechazo ingreso?'),
        ),
        migrations.AlterField(
            model_name='identificador',
            name='sector',
            field=models.CharField(blank=True, choices=[('1', 'AIS Gracia'), ('2', 'AIS Dreta'), ('3', 'AIS Guinardó')], max_length=1, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Sin tristeza'), (1, '1.'), (2, '2. Parece decaído/a pero se anima sin dificultad'), (3, '3.'), (4, '4. Parece triste y desgraciado/a la mayor parte del tiempo'), (5, '5.'), (6, '6.Parece siempre desgraciado/a. Extremadamente abatido/a')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Tristeza esporádica según las circunstancias'), (1, '1.'), (2, '2. Triste o decaído/a, pero se anima sin dificultad'), (3, '3.'), (4, '4. Sentimientos generalizados de tristeza o melancolía. El estado de ánimo todavía se ve influido por circunstancias externas'), (5, '5.'), (6, '6. Abatimiento, desdicha o tristeza continuada o invariable')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Apacible. Sólo tensión interna pasajera'), (1, '1.'), (2, '2. Sentimientos ocacionales de nerviosismo y maletar indefinido'), (3, '3.'), (4, '4. Sentimientos continuados de tensión interna o pánico intermitente que el sujeto sólo puede dominar con alguna dificultad'), (5, '5.'), (6, '6. Terror o angustia tenaz. Pánico irresistible')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Duerme como siempre'), (1, '1.'), (2, '2. Ligera dificultad para dormirse o sueño ligeramente reducido, sueño ligero o perturbado'), (3, '3.'), (4, '4. Sueño reducido o interrumpido durante al menos 2 h'), (5, '5.'), (6, '6. Menos de 2 o 3 h de sueño')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Apetito normal o aumentado'), (1, '1.'), (2, '2. Apetito ligeramente reducido'), (3, '3.'), (4, '4. Sin apetito. La comida es insípida'), (5, '5.'), (6, '6. Necesita persuasión para comer algo')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Ninguna dificultad para concentrarse'), (1, '1.'), (2, '2. Dificultades ocasionales para centrar los pensamientos'), (3, '3.'), (4, '4. Dificultades para concentrarse y seguir una idea que reduce la capacidad de leer o mantener una conversación'), (5, '5.'), (6, '6. Incapaz de leer o mantener una conversación si no es con gran dificultad')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Casi sin dificultad para empezar algo. Sin apatía'), (1, '1.'), (2, '2. Dificultades para empezar actividades'), (3, '3.'), (4, '4. Dificultades para empezar actividades rutinarias sencillas que se llevan a cabo con esfuerzo'), (5, '5.'), (6, '6. Lasitud total. Incapaz de hacer nada sin ayuda')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Interés normal por el entorno y por otras personas'), (1, '1.'), (2, '2. Menor capacidad para disfrutar de las cosas que normalmen te le interesan'), (3, '3.'), (4, '4. Pérdida de interés por el entorno. Pérdida de sentimientos respecto a los amigos y conocidos'), (5, '5.'), (6, '6. La experiencia de estar emocionalmente paralizado, incapacidad para sentir enfado, pena o placer y una total o incluso dolorosa falta de sentimientos hacia los parientes próximos y amigos')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Sin pensamientos pesimistas'), (1, '1.'), (2, '2. Ideas variables de fracaso, autorreproche o autodesprecio'), (3, '3.'), (4, '4. Autoacusaciones persistentes o ideas definidas, pero aún racionales, de culpabilidad o pecado. Cada vez más pesimista respecto al futuro'), (5, '5.'), (6, '6. Alucinaciones de ruina, remordimiento o pecado irredimible. Autoacusaciones que son absurdas e inquebrantables')], default=0),
        ),
        migrations.AlterField(
            model_name='madrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(choices=[(0, '0. Disfruta de la vida o la acepta tal como viene'), (1, '1.'), (2, '2. Cansado de vivir. Sólo pensamientos suicidas pasajeros'), (3, '3.'), (4, '4. Probablemente  estaría  mejor  muerto/a. Los  pensamientos suicidas son habituales, y se considera el suicidio como una posible solución, pero sin ninguna intención o plan específico'), (5, '5.'), (6, '6. Planes explícitos de suicidio cuando se presente una oportunidad. Preparativos activos para el suicidio')], default=0),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g01',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g02',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g03',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g04',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g05',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g06',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g07',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g08',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g09',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g10',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g11',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g12',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g13',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g14',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g15',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_g16',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n01',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n02',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n03',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n04',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n05',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n06',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_n07',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p01',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p02',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p03',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p04',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p05',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p06',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='panss',
            name='item_p07',
            field=models.PositiveSmallIntegerField(choices=[(1, '1.Ausente'), (2, '2.Mínimo'), (3, '3.Ligero'), (4, '4.Moderado'), (5, '5.Moderado severo'), (6, '6.Severo'), (7, '7.Extremo')], default=1),
        ),
        migrations.AlterField(
            model_name='satis',
            name='autor',
            field=models.CharField(blank=True, choices=[('PAC', 'Paciente'), ('FAM', 'Familia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Muy Poca'), (2, '2.Poca'), (3, '3.Normal'), (4, '4.Bastante'), (5, '5.Mucha')], null=True),
        ),
        migrations.AlterField(
            model_name='satis',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Siempre ingresaria en hosp'), (2, '2.Casi siempre hosp '), (3, '3.Me daría igual'), (4, '4.Casi siempre dom'), (5, '5.Siempre dom')], null=True),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='dosis final (mg/dia)'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='mg_dia_inicio',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='dosis inicio (mg/dia)'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='motivo',
            field=models.CharField(blank=True, choices=[('01', 'Abandono de tratamiento'), ('02', 'Falta de respuesta'), ('03', 'Efecto adverso EP'), ('04', 'Efecto adverso digestivo'), ('05', 'Efecto adverso hematologico'), ('06', 'Efecto adverso autonómico'), ('07', 'Otro efecto adverso'), ('08', 'Respuesta parcial'), ('99', 'NE')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_1',
            field=models.IntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d1_6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d2_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d3_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d4_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d5_8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_1',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_2',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_3',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_4',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_5',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_6',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_7',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='who_das',
            name='d6_8',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1.Ninguna'), (2, '2.Leve'), (3, '3.Moderada'), (4, '4.Severa'), (5, '5.Extrema / no puede')], null=True),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_01',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Posible o moderada, sólo cuando se le pregunta'), (2, '2.Clara aunque subjetiva y apropiada al contenido: optimista, seguro de sí mismo/a, alegre'), (3, '3.Elevada e inapropiada'), (4, '4.Claramente eufórico/a, risa inadecuada, canta durante la entrevista, etc.')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_02',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.Subjetivamente aumentada'), (2, '2.Vigoroso/a, hipergestual'), (3, '3.Energía excesiva, hiperactividad fluctuante, inquietud (puede ser calmado/a)'), (4, '4.Agitación o hiperactividad constante (no puede ser calmado/a)')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_03',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Normal, no aumentado'), (1, '1.Posible o moderadamente aumentado'), (2, '2.Claro aumento al preguntar'), (3, '3.Referido como elevado de forma espontánea, contenido sexual del discurso, preocupación por temas sexuales'), (4, '4.Actos o incitaciones sexuales evidentes (hacia pacientes, personal o entrevistador)')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_04',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No reducido'), (1, '1.Disminución en menos de 1 ,hora'), (2, '2.Disminución en más de 1 hora'), (3, '3.Refiere disminución de la necesidad de dormir'), (4, '4.Niega necesidad de dormir')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_05',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente'), (1, '1.'), (2, '2.Subjetivamente aumentada'), (3, '3.'), (4, '4.Irritabilidad fluctuante durante la entrevista, episodios recientes de rabia o enfado'), (5, '5.'), (6, '6.Predominantemente irritable durante la entrevista, brusco y cortante'), (7, '7.'), (8, '8.Hostil, no colaborador/a, entrevista imposible')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_06',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.No aumentada'), (1, '1.'), (2, '2.Sensación de locuacidad'), (3, '3.'), (4, '4.Aumentada de forma fluctuante, verborrea ocasional'), (5, '5.'), (6, '6.Claramente aumentada en ritmo y cantidad, difícil de interrumpir, intrusiva'), (7, '7.'), (8, '8.Verborrea ininterrumpible y continua')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_07',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausentes'), (1, '1.Circunstancialidad, distraibilidad moderada, aceleración del pensamiento'), (2, '2.Distraibilidad clara, descarrilamiento, taquipsiquia'), (3, '3.Fuga de ideas, tangencialidad, discurso difícil de seguir, rimas, ecolalia'), (4, '4.Incoherencia, ininteligibilidad, comunicación imposible')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_08',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausentes'), (1, '1.'), (2, '2.Planes discutibles, nuevos intereses'), (3, '3.'), (4, '4.Proyectos especiales, misticismo'), (5, '5.'), (6, '6.Ideas grandiosas o paranoides, ideas de referencia'), (7, '7.'), (8, '8.Delirios, alucinaciones')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_09',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Ausente, colaborador/a'), (1, '1.'), (2, '2.Sarcástico/a, enfático/a, lacónico/a'), (3, '3.'), (4, '4.Querulante, pone en guardia'), (5, '5.'), (6, '6.Amenaza al entrevistador, habla a gritos, entrevista difícil'), (7, '7.'), (8, '8.Claramente agresivo/a, destructivo/a, entrevista imposible')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_10',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Higiene e indumentaria apropiada '), (1, '1.Ligeramente descuidada'), (2, '2.Mal arreglado/a, moderadamente despeinado/a, indumentaria sobrecargada'), (3, '3.Despeinado/a, semidesnudo/a, maquillaje llamativo'), (4, '4.Completamente desaseado/a, adornado/a, indumentaria extravagante')], default=0),
        ),
        migrations.AlterField(
            model_name='ymrs',
            name='item_11',
            field=models.PositiveSmallIntegerField(choices=[(0, '0.Presente, admite la enfermedad, acepta tratamiento'), (1, '1.Según él/ella, posiblemente enfermo/a'), (2, '2.Admite cambio de conducta, pero niega enfermedad'), (3, '3.Admite posible cambio de conducta, niega enfermedad'), (4, '4.Niega cualquier cambio de conduct')], default=0),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_01',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_02',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_03',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_04',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_05',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_06',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_07',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_08',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_09',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_10',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_11',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_12',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_13',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_14',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_15',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_16',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_17',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_18',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_19',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_20',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_21',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
        migrations.AlterField(
            model_name='zarit',
            name='item_22',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '0. Nunca'), (1, '1. Casi nunca'), (2, '2. A veces'), (3, '3. Bastantes veces'), (4, '4. Siempre')], null=True),
        ),
    ]
