# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-09-16 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0084_auto_20190914_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificador',
            name='psiquiatra',
            field=models.CharField(blank=True, choices=[('AKG', 'A. Keymer'), ('AMB', 'A. Martin'), ('SVC', 'S. Vieira'), ('NBG', 'N. Bague')], max_length=3, verbose_name='psiquiatra'),
        ),
    ]
